USE [master]
GO
/****** Object:  Database [MicrosoftStore]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE DATABASE [MicrosoftStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MicrosoftStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MicrosoftStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MicrosoftStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MicrosoftStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MicrosoftStore] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MicrosoftStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MicrosoftStore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MicrosoftStore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MicrosoftStore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MicrosoftStore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MicrosoftStore] SET ARITHABORT OFF 
GO
ALTER DATABASE [MicrosoftStore] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MicrosoftStore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MicrosoftStore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MicrosoftStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MicrosoftStore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MicrosoftStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MicrosoftStore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MicrosoftStore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MicrosoftStore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MicrosoftStore] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MicrosoftStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MicrosoftStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MicrosoftStore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MicrosoftStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MicrosoftStore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MicrosoftStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MicrosoftStore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MicrosoftStore] SET RECOVERY FULL 
GO
ALTER DATABASE [MicrosoftStore] SET  MULTI_USER 
GO
ALTER DATABASE [MicrosoftStore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MicrosoftStore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MicrosoftStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MicrosoftStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MicrosoftStore] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MicrosoftStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MicrosoftStore', N'ON'
GO
ALTER DATABASE [MicrosoftStore] SET QUERY_STORE = OFF
GO
USE [MicrosoftStore]
GO
/****** Object:  Table [dbo].[Apps]    Script Date: 10/17/2021 2:20:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Apps](
	[AppID] [int] NOT NULL,
	[NameOfApp] [varchar](50) NOT NULL,
	[Publisher] [varchar](50) NOT NULL,
	[Genre] [varchar](20) NOT NULL,
	[ListedPrice] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[AppID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 10/17/2021 2:20:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] NOT NULL,
	[FullName] [varchar](50) NOT NULL,
	[Address] [varchar](50) NULL,
	[LocationID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Games]    Script Date: 10/17/2021 2:20:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Games](
	[GameID] [int] NOT NULL,
	[NameOfGame] [varchar](50) NOT NULL,
	[Publisher] [varchar](50) NOT NULL,
	[Genre] [varchar](20) NOT NULL,
	[ESRBRating] [varchar](10) NOT NULL,
	[ListedPrice] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[GameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Locations]    Script Date: 10/17/2021 2:20:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[LocationID] [int] NOT NULL,
	[City] [varchar](50) NULL,
	[State] [varchar](20) NULL,
	[Country] [varchar](30) NULL,
	[ZipCode] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[LocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PurchaseDetails]    Script Date: 10/17/2021 2:20:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PurchaseDetails](
	[PurchaseDetailsID] [int] NOT NULL,
	[PurchaseID] [int] NOT NULL,
	[GameID] [int] NULL,
	[AppID] [int] NULL,
	[PurchaseDate] [varchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PurchaseDetailsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Purchases]    Script Date: 10/17/2021 2:20:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Purchases](
	[PurchaseID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
	[LocationID2] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PurchaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [idx_LocationID]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE NONCLUSTERED INDEX [idx_LocationID] ON [dbo].[Customers]
(
	[LocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_AppID]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE NONCLUSTERED INDEX [idx_AppID] ON [dbo].[PurchaseDetails]
(
	[AppID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_GameID]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE NONCLUSTERED INDEX [idx_GameID] ON [dbo].[PurchaseDetails]
(
	[GameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_PurchaseID]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE NONCLUSTERED INDEX [idx_PurchaseID] ON [dbo].[PurchaseDetails]
(
	[PurchaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_CustomerID]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE NONCLUSTERED INDEX [idx_CustomerID] ON [dbo].[Purchases]
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_LocationID2]    Script Date: 10/17/2021 2:20:35 AM ******/
CREATE NONCLUSTERED INDEX [idx_LocationID2] ON [dbo].[Purchases]
(
	[LocationID2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_LocationID] FOREIGN KEY([LocationID])
REFERENCES [dbo].[Locations] ([LocationID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_LocationID]
GO
ALTER TABLE [dbo].[PurchaseDetails]  WITH CHECK ADD  CONSTRAINT [FK_AppID] FOREIGN KEY([AppID])
REFERENCES [dbo].[Apps] ([AppID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PurchaseDetails] CHECK CONSTRAINT [FK_AppID]
GO
ALTER TABLE [dbo].[PurchaseDetails]  WITH CHECK ADD  CONSTRAINT [FK_GameID] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PurchaseDetails] CHECK CONSTRAINT [FK_GameID]
GO
ALTER TABLE [dbo].[PurchaseDetails]  WITH CHECK ADD  CONSTRAINT [FK_PurchaseID] FOREIGN KEY([PurchaseID])
REFERENCES [dbo].[Purchases] ([PurchaseID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PurchaseDetails] CHECK CONSTRAINT [FK_PurchaseID]
GO
ALTER TABLE [dbo].[Purchases]  WITH CHECK ADD  CONSTRAINT [FK_CustomerID] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([CustomerID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Purchases] CHECK CONSTRAINT [FK_CustomerID]
GO
ALTER TABLE [dbo].[Purchases]  WITH CHECK ADD  CONSTRAINT [FK_LocationID2] FOREIGN KEY([LocationID2])
REFERENCES [dbo].[Locations] ([LocationID])
GO
ALTER TABLE [dbo].[Purchases] CHECK CONSTRAINT [FK_LocationID2]
GO
USE [master]
GO
ALTER DATABASE [MicrosoftStore] SET  READ_WRITE 
GO
